import Fuse from 'fuse.js';
import { logger } from '../utils/logger.js';

export interface LeadRecord {
  // Identity
  workspaceId: string;
  jobId: string;
  companyName: string;
  companyDomain?: string;
  website?: string;
  industry?: string;
  address?: { city?: string; state?: string; country?: string; fullText?: string };

  // Contact data
  emails: Array<{
    address: string;
    type: string;
    confidence: number;
    source: string;
    name?: string;
    title?: string;
    department?: string;
  }>;
  phones: Array<{
    raw: string;
    normalized?: string;
    type?: string;
    countryCode?: string;
    source: string;
  }>;
  socialProfiles?: { linkedinUrl?: string };
  contactSummary?: {
    totalContacts: number;
    topContact?: { fullName: string; title: string; seniority: string };
  };

  // Metadata
  osint?: Record<string, unknown>;
  sources: Array<{ url: string; type: string; scrapedAt: Date; confidence: number }>;
  rawSnippets: string[];
  rankScore: number;
  completenessScore: number;
  isDuplicate: boolean;
  mergedIntoId?: string;
  tags: string[];
  /** Query-specific fact values keyed by outputSchema column key. */
  facts?: Record<string, {
    value: string | number | boolean | string[] | null;
    unit?: string;
    sourceUrl?: string;
    confidence?: number;
    raw?: string;
  }>;
  /** Fraction 0-1 of REQUIRED schema columns that have a value. */
  schemaFulfillmentPct?: number;
  /** The agent's one-line justification for emitting this lead. Passed
   *  from `write_lead` tool call → persisted on the Lead so the detail
   *  drawer can show "why this lead" alongside the grader's reason. */
  agentReasoning?: string;
  /** Hybrid-discovery only. 2-3 sentence explanation of why this company fits
   *  the user's offering, generated by the discovery LLM call. Surfaces in UI. */
  fitReason?: string;
  /** Hybrid-discovery only. 1-3 short signal tags (e.g. "Series A", "50-200 staff",
   *  "rapid hiring"). Surfaces as badges in the lead drawer. */
  signals?: string[];
}

export function deduplicateLeads(leads: LeadRecord[], threshold = 0.25): LeadRecord[] {
  if (leads.length === 0) return [];

  // Pass 1: exact domain dedup — keep most complete (most emails + phones)
  const byDomain = new Map<string, LeadRecord>();
  const noDomain: LeadRecord[] = [];

  for (const lead of leads) {
    const domain = lead.companyDomain?.toLowerCase();
    if (!domain) { noDomain.push(lead); continue; }
    const existing = byDomain.get(domain);
    if (!existing) { byDomain.set(domain, lead); continue; }
    // Merge: keep more complete record as primary, merge emails/phones
    const merged = mergeLeads(existing, lead);
    byDomain.set(domain, merged);
  }

  const deduped = [...byDomain.values(), ...noDomain];

  // Pass 2: fuzzy company name dedup (only on records without domain)
  const withDomain = deduped.filter(l => l.companyDomain);
  const withoutDomain = deduped.filter(l => !l.companyDomain);

  if (withoutDomain.length < 2) return deduped;

  const fuse = new Fuse(withoutDomain, { keys: ['companyName'], threshold });
  const processed = new Set<number>();
  const fuzzyResult: LeadRecord[] = [];

  for (let i = 0; i < withoutDomain.length; i++) {
    if (processed.has(i)) continue;
    const lead = withoutDomain[i]!;
    const matches = fuse.search(lead.companyName);
    // Find matches that aren't self
    const dupes = matches.filter(m => m.refIndex !== i && !processed.has(m.refIndex));
    if (dupes.length > 0) {
      let merged = lead;
      for (const dupe of dupes) {
        merged = mergeLeads(merged, withoutDomain[dupe.refIndex]!);
        processed.add(dupe.refIndex);
        // Mark the dupe
        withoutDomain[dupe.refIndex]!.isDuplicate = true;
        withoutDomain[dupe.refIndex]!.mergedIntoId = lead.companyName; // placeholder, real ID set in leadWriter
      }
      fuzzyResult.push(merged);
    } else {
      fuzzyResult.push(lead);
    }
    processed.add(i);
  }

  logger.info('Deduplication complete', {
    input: leads.length,
    output: withDomain.length + fuzzyResult.length,
  });

  return [...withDomain, ...fuzzyResult];
}

function mergeLeads(primary: LeadRecord, secondary: LeadRecord): LeadRecord {
  // Merge emails (deduplicate by address)
  const emailMap = new Map(primary.emails.map(e => [e.address, e]));
  for (const e of secondary.emails) {
    if (!emailMap.has(e.address)) emailMap.set(e.address, e);
  }

  // Merge phones (deduplicate by normalized or raw)
  const phoneMap = new Map(primary.phones.map(p => [p.normalized ?? p.raw, p]));
  for (const p of secondary.phones) {
    const key = p.normalized ?? p.raw;
    if (!phoneMap.has(key)) phoneMap.set(key, p);
  }

  return {
    ...primary,
    emails: [...emailMap.values()],
    phones: [...phoneMap.values()],
    sources: [...primary.sources, ...secondary.sources],
    rawSnippets: [...new Set([...primary.rawSnippets, ...secondary.rawSnippets])].slice(0, 20),
    socialProfiles: primary.socialProfiles?.linkedinUrl ? primary.socialProfiles : secondary.socialProfiles,
    osint: primary.osint ?? secondary.osint,
    website: primary.website ?? secondary.website,
  };
}
